name: my_flutter_basic
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # 国际化
  flutter_localizations:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # 获取设备信息
  my_device_info:
    path: ./plugins/my_device_info

  # 自定义方法集合
  my_utils:
    path: ./plugins/my_utils

  # 深度链接
  my_deep_link:
      path: ./plugins/my_deep_link

  # 图片处理
  my_gallery:
    path: ./plugins/my_gallery

  # 常用组件
  my_widgets:
    path: ./plugins/my_widgets

  # GetX
  get: ^5.0.0-release-candidate-9.2.1

  # svg
  flutter_svg: ^2.0.10+1

  # lottie
  lottie: ^3.2.0

  # 音频/音效
  audioplayers: ^6.1.0

  # 热更新
  shorebird_code_push: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/dark/
    - assets/images/light/
    - assets/svg/
    - assets/svg/dark/
    - assets/svg/light/
    - assets/lottie/
    - assets/lottie/dark/
    - assets/lottie/light/
    - assets/audios/
    - assets/common/
    - shorebird.yaml

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
