part of 'my_locale.dart';

const Map<String, String> en = {
  // 公共
  MyLanguage.sendCode: 'Send Code',
  MyLanguage.send: 'Send',
  MyLanguage.album: 'Album',
  MyLanguage.save: 'Save',
  MyLanguage.confirm: 'Confirm',
  MyLanguage.confirmLater: 'Later',
  MyLanguage.goConfirm: 'Confirm',
  MyLanguage.cancel: 'Cancel',
  MyLanguage.noData: 'No Data',
  MyLanguage.delete: 'Delete',
  MyLanguage.retry: 'Retry',
  MyLanguage.reply: 'Reply',
  MyLanguage.search: 'Search',
  MyLanguage.saveImageToGallery: 'Save to Gallery',
  MyLanguage.saveImageToGalleryFailed: 'Save to Gallery Failed',
  MyLanguage.saveImageToGallerySuccess: 'Saved to Gallery',
  MyLanguage.noStoragePermission: 'Please enable the relevant permissions',
  MyLanguage.reset: 'Reset',
  MyLanguage.copy: 'Copy',
  MyLanguage.isContinue: 'Are you sure to continue?',
  MyLanguage.yes: 'Yes',
  MyLanguage.no: 'No',
  MyLanguage.collectType: 'Collect Type',
  MyLanguage.realNameAlert: 'For your financial security, please complete identity verification.',
  MyLanguage.goRealName: 'Verify Now',
  MyLanguage.tryItNow: 'Try it now',
  MyLanguage.activityClosed: 'The activity was closed',
  MyLanguage.connecting: 'connecting...',
  MyLanguage.connectFailed: 'Failed to initialize the connection',
  MyLanguage.videoPlayerLoading: 'Loading...',
  MyLanguage.fileSizeOut: 'File must not exceed %s MB"',

  MyLanguage.languageEnglish: 'English',
  MyLanguage.languageChinese: 'Chinese (Simplified)',
  MyLanguage.themeDark: 'Dark',
  MyLanguage.themeLight: 'Light',
  MyLanguage.themeSystem: 'Follow System',
};
